export const TILE_SIZE = 48; // Pixels per tile

export const TERRAIN = {
  PLAIN: 0,
  FOREST: 1,
  MOUNTAIN: 2,
  WATER: 3,
  CASTLE: 4,
  VILLAGE: 5,
  // Extended Terrain Types
  WATER_SHIMMER: 101,
  WATER_SHIMMER_2: 102,
  WATER_R_LAND: 103,
  WATER_RB_LAND: 104,
  WATER_BR_LAND: 105,
  WATER_B_LAND: 106,
  WATER_BL_LAND: 107,
  WATER_LB_LAND: 108,
  WATER_L_LAND: 109,
  WATER_TR_LAND: 110,
  WATER_T_LAND: 111,
  WATER_TL_LAND: 112,
  WATER_T_R_LAND: 113,
  WATER_T_L_LAND: 114,
  FOREST_3: 115,
  FOREST_2: 116,
  MOUNTAIN_HIGH: 117,
  SNOW_PLAIN: 118,
  MOUNTAIN_SMALL: 119,
  SNOW_ROAD_H: 120,
  SNOW_ROAD_V: 121,
  SNOW_ROAD_CROSS: 122,
  SNOW_ROAD_L_B: 123,
  SNOW_ROAD_L_T: 124,
  SNOW_ROAD_T_R: 125,
  SNOW_ROAD_B_R: 126,
  VILLAGE_RUIN: 127,
  BRIDGE_H: 128,
  BRIDGE_V: 129,
  VILLAGE_HEAL: 130,
  TEMPLE_HEAL: 131,
  SNOW_BUILDING_1: 132,
  SNOW_BUILDING_2: 133,
  SNOW_BUILDING_3: 134,
  SNOW_BUILDING_4: 135,
  TOWN: 136,
  CASTLE_2: 137,
  WATER_TL_BL_LAND: 138,
  WATER_BL_BR_LAND: 139,
  WATER_TR_BR_LAND: 140,
  WATER_TL_TR_LAND: 141,
  WATER_TL_BR_LAND: 142,
  WATER_BL_TR_LAND: 143,
  WATER_TL_TR_BL_LAND: 144,
  WATER_TL_TR_BR_LAND: 145,
  WATER_TR_BL_BR_LAND: 146,
  WATER_TL_BL_BR_LAND: 147,
  WATER_CORNERS_LAND: 148,
  WATER_BL_BR_T_LAND: 149,
  WATER_TL_TR_B_LAND: 150,
  WATER_TL_BL_R_LAND: 151,
  WATER_L_TR_BR_LAND: 152,
  WATER_T_BR_LAND: 153,
  WATER_T_BL_LAND: 154,
  WATER_TL_B_LAND: 155,
  WATER_TR_B_LAND: 156,
  WATER_TL_R_LAND: 157,
  WATER_BL_R_LAND: 158,
  WATER_L_TR_LAND: 159,
  WATER_L_BR_LAND: 160,
  WATER_T_R_BL_LAND: 161,
  WATER_TL_R_B_LAND: 162,
  WATER_L_B_TR_LAND: 163,
  WATER_L_T_BR_LAND: 164,
  WATER_T_B_LAND: 165,
  WATER_L_R_LAND: 166,
  WATER_T_R_B_LAND: 167,
  WATER_T_L_B_LAND: 168,
  WATER_L_T_R_LAND: 169,
  WATER_L_B_R_LAND: 170,
  WATER_ALL_LAND: 171,
  SNOW_ROAD_T_B_R: 172,
  SNOW_ROAD_L_T_R: 173,
  SNOW_ROAD_L_R_B: 174,
  SNOW_ROAD_T_B_L: 175,
  SNOW_ROAD_END_T: 176,
  SNOW_ROAD_END_B: 177,
  SNOW_ROAD_END_R: 178,
  SNOW_ROAD_END_L: 179,
  TEMPLE: 180,
  REEF_3: 181,
  REEF_2: 182,
  TEMPLE_WATER: 183
};

// export const UNIT_TYPES = {
//   SOLDIER: 'soldier',
//   ARCHER: 'archer',
//   KNIGHT: 'knight', // Added missing type
//   MAGE: 'mage',
//   KING: 'king',
//   SKELETON: 'skeleton',
//   WOLF: 'wolf',
//   GOLEM: 'golem',
//   WISP: 'wisp',
//   CATAPULT: 'catapult',
//   DRAGON: 'dragon'
// };

// Merged UNIT_TYPES to avoid duplication and ensure all types are present
export const UNIT_TYPES = {
  SOLDIER: 'soldier',
  ARCHER: 'archer',
  // MAGE: 'mage', // Removed
  KING: 'king',
  SKELETON: 'skeleton',
  WOLF: 'wolf',
  // GOLEM: 'golem', // Removed
  // WISP: 'wisp', // Removed
  CATAPULT: 'catapult',
  DRAGON: 'dragon',
  // Additional types from previous definition
  GHOST: 'ghost',
  SLIME: 'slime',
  MERMAID: 'mermaid',
  WATER_ELEMENTAL: 'water_elemental',
  DARK_MAGE: 'dark_mage',
  SORCERESS: 'sorceress',
  PALADIN: 'paladin',
  ELF: 'elf',
  BERSERKER: 'berserker',
  STONE_GOLEM: 'stone_golem',
  ICE_ELEMENTAL: 'ice_elemental',
  WOLF_RIDER: 'wolf_rider',
  DRUID: 'druid',
  WISDOM_CRYSTAL: 'wisdom_crystal'
};

export const TERRAIN_SPRITES = {
  [TERRAIN.PLAIN]: 't18',
  [TERRAIN.FOREST]: 't15',
  [TERRAIN.MOUNTAIN]: 't17',
  [TERRAIN.WATER]: 't0',
  [TERRAIN.CASTLE]: 't37',
  [TERRAIN.VILLAGE]: 't30',
  [TERRAIN.SNOW_ROAD_H]: 't20',
  [TERRAIN.SNOW_ROAD_V]: 't21',
  [TERRAIN.SNOW_ROAD_CROSS]: 't22',
  [TERRAIN.SNOW_ROAD_L_B]: 't23',
  [TERRAIN.SNOW_ROAD_L_T]: 't24',
  [TERRAIN.SNOW_ROAD_T_R]: 't25',
  [TERRAIN.SNOW_ROAD_B_R]: 't26',
  [TERRAIN.VILLAGE_RUIN]: 't27',
  [TERRAIN.BRIDGE_H]: 't28',
  [TERRAIN.BRIDGE_V]: 't29',
  [TERRAIN.VILLAGE]: 't30',
  [TERRAIN.TEMPLE_HEAL]: 't31',
  [TERRAIN.SNOW_BUILDING_1]: 't32',
  [TERRAIN.SNOW_BUILDING_2]: 't33',
  [TERRAIN.SNOW_BUILDING_3]: 't34',
  [TERRAIN.SNOW_BUILDING_4]: 't35',
  [TERRAIN.TOWN]: 't36',
  [TERRAIN.CASTLE]: 't37',
  [TERRAIN.WATER_TL_BL_LAND]: 't38',
  [TERRAIN.WATER_BL_BR_LAND]: 't39',
  [TERRAIN.WATER_TR_BR_LAND]: 't40',
  [TERRAIN.WATER_TL_TR_LAND]: 't41',
  [TERRAIN.WATER_TL_BR_LAND]: 't42',
  [TERRAIN.WATER_BL_TR_LAND]: 't43',
  [TERRAIN.WATER_TL_TR_BL_LAND]: 't44',
  [TERRAIN.WATER_TL_TR_BR_LAND]: 't45',
  [TERRAIN.WATER_TR_BL_BR_LAND]: 't46',
  [TERRAIN.WATER_TL_BL_BR_LAND]: 't47',
  [TERRAIN.WATER_CORNERS_LAND]: 't48',
  [TERRAIN.WATER_BL_BR_T_LAND]: 't49',
  [TERRAIN.WATER_TL_TR_B_LAND]: 't50',
  [TERRAIN.WATER_TL_BL_R_LAND]: 't51',
  [TERRAIN.WATER_L_TR_BR_LAND]: 't52',
  [TERRAIN.WATER_T_BR_LAND]: 't53',
  [TERRAIN.WATER_T_BL_LAND]: 't54',
  [TERRAIN.WATER_TL_B_LAND]: 't55',
  [TERRAIN.WATER_TR_B_LAND]: 't56',
  [TERRAIN.WATER_TL_R_LAND]: 't57',
  [TERRAIN.WATER_BL_R_LAND]: 't58',
  [TERRAIN.WATER_L_TR_LAND]: 't59',
  [TERRAIN.WATER_L_BR_LAND]: 't60',
  [TERRAIN.WATER_T_R_BL_LAND]: 't61',
  [TERRAIN.WATER_TL_R_B_LAND]: 't62',
  [TERRAIN.WATER_L_B_TR_LAND]: 't63',
  [TERRAIN.WATER_L_T_BR_LAND]: 't64',
  [TERRAIN.WATER_T_B_LAND]: 't65',
  [TERRAIN.WATER_L_R_LAND]: 't66',
  [TERRAIN.WATER_T_R_B_LAND]: 't67',
  [TERRAIN.WATER_T_L_B_LAND]: 't68',
  [TERRAIN.WATER_L_T_R_LAND]: 't69',
  [TERRAIN.WATER_L_B_R_LAND]: 't70',
  [TERRAIN.WATER_ALL_LAND]: 't71',
  [TERRAIN.SNOW_ROAD_T_B_R]: 't72',
  [TERRAIN.SNOW_ROAD_L_T_R]: 't73',
  [TERRAIN.SNOW_ROAD_L_R_B]: 't74',
  [TERRAIN.SNOW_ROAD_T_B_L]: 't75',
  [TERRAIN.SNOW_ROAD_END_T]: 't76',
  [TERRAIN.SNOW_ROAD_END_B]: 't77',
  [TERRAIN.SNOW_ROAD_END_R]: 't78',
  [TERRAIN.SNOW_ROAD_END_L]: 't79',
  [TERRAIN.TEMPLE]: 't80',
  [TERRAIN.REEF_3]: 't81',
  [TERRAIN.REEF_2]: 't82',
  [TERRAIN.TEMPLE_WATER]: 't83',
  [TERRAIN.WATER_SHIMMER]: 't1',
  [TERRAIN.WATER_SHIMMER_2]: 't2',
  [TERRAIN.WATER_R_LAND]: 't3',
  [TERRAIN.WATER_RB_LAND]: 't4',
  [TERRAIN.WATER_BR_LAND]: 't5',
  [TERRAIN.WATER_B_LAND]: 't6',
  [TERRAIN.WATER_BL_LAND]: 't7',
  [TERRAIN.WATER_LB_LAND]: 't8',
  [TERRAIN.WATER_L_LAND]: 't9',
  [TERRAIN.WATER_TR_LAND]: 't10',
  [TERRAIN.WATER_T_LAND]: 't11',
  [TERRAIN.WATER_TL_LAND]: 't12',
  [TERRAIN.FOREST_3]: 't13',
  [TERRAIN.FOREST_2]: 't14',
  [TERRAIN.MOUNTAIN_HIGH]: 't16',
  [TERRAIN.SNOW_PLAIN]: 't19',
  [TERRAIN.MOUNTAIN_SMALL]: 't17',
  [TERRAIN.VILLAGE_HEAL]: 't30',
  [TERRAIN.CASTLE_2]: 't37',
};

export const TERRAIN_COLORS = {
  [TERRAIN.PLAIN]: '#90EE90',
  [TERRAIN.FOREST]: '#228B22',
  [TERRAIN.MOUNTAIN]: '#808080',
  [TERRAIN.WATER]: '#4682B4',
  [TERRAIN.CASTLE]: '#8B4513',
  [TERRAIN.VILLAGE]: '#DEB887',
  [TERRAIN.WATER_SHIMMER]: '#4682B4',
  [TERRAIN.WATER_SHIMMER_2]: '#4682B4',
  [TERRAIN.FOREST_3]: '#228B22',
  [TERRAIN.FOREST_2]: '#228B22',
  [TERRAIN.MOUNTAIN_HIGH]: '#808080',
  [TERRAIN.SNOW_PLAIN]: '#F0FFFF',
  [TERRAIN.MOUNTAIN_SMALL]: '#808080',
  [TERRAIN.VILLAGE_HEAL]: '#DEB887',
  [TERRAIN.CASTLE_2]: '#8B4513',
  [TERRAIN.TEMPLE]: '#D3D3D3',
  [TERRAIN.REEF_3]: '#000080',
  [TERRAIN.REEF_2]: '#000080',
  [TERRAIN.TEMPLE_WATER]: '#D3D3D3',
  [TERRAIN.TOWN]: '#CD853F',
  [TERRAIN.VILLAGE_RUIN]: '#696969',
  [TERRAIN.BRIDGE_H]: '#8B4513',
  [TERRAIN.BRIDGE_V]: '#8B4513',
  [TERRAIN.SNOW_BUILDING_1]: '#CD853F',
  [TERRAIN.SNOW_BUILDING_2]: '#CD853F',
  [TERRAIN.SNOW_BUILDING_3]: '#CD853F',
  [TERRAIN.SNOW_BUILDING_4]: '#CD853F',
  [TERRAIN.WATER_TL_BL_LAND]: '#4682B4',
  [TERRAIN.WATER_BL_BR_LAND]: '#4682B4',
  [TERRAIN.WATER_TR_BR_LAND]: '#4682B4',
  [TERRAIN.WATER_TL_TR_LAND]: '#4682B4',
  [TERRAIN.WATER_TL_BR_LAND]: '#4682B4',
  [TERRAIN.WATER_BL_TR_LAND]: '#4682B4',
  [TERRAIN.WATER_TL_TR_BL_LAND]: '#4682B4',
  [TERRAIN.WATER_TL_TR_BR_LAND]: '#4682B4',
  [TERRAIN.WATER_TR_BL_BR_LAND]: '#4682B4',
  [TERRAIN.WATER_TL_BL_BR_LAND]: '#4682B4',
  [TERRAIN.WATER_CORNERS_LAND]: '#4682B4',
  [TERRAIN.WATER_BL_BR_T_LAND]: '#4682B4',
  [TERRAIN.WATER_TL_TR_B_LAND]: '#4682B4',
  [TERRAIN.WATER_TL_BL_R_LAND]: '#4682B4',
  [TERRAIN.WATER_L_TR_BR_LAND]: '#4682B4',
  [TERRAIN.WATER_T_BR_LAND]: '#4682B4',
  [TERRAIN.WATER_T_BL_LAND]: '#4682B4',
  [TERRAIN.WATER_TL_B_LAND]: '#4682B4',
  [TERRAIN.WATER_TR_B_LAND]: '#4682B4',
  [TERRAIN.WATER_TL_R_LAND]: '#4682B4',
  [TERRAIN.WATER_BL_R_LAND]: '#4682B4',
  [TERRAIN.WATER_L_TR_LAND]: '#4682B4',
  [TERRAIN.WATER_L_BR_LAND]: '#4682B4',
  [TERRAIN.WATER_T_R_BL_LAND]: '#4682B4',
  [TERRAIN.WATER_TL_R_B_LAND]: '#4682B4',
  [TERRAIN.WATER_L_B_TR_LAND]: '#4682B4',
  [TERRAIN.WATER_L_T_BR_LAND]: '#4682B4',
  [TERRAIN.WATER_T_B_LAND]: '#4682B4',
  [TERRAIN.WATER_L_R_LAND]: '#4682B4',
  [TERRAIN.WATER_T_R_B_LAND]: '#4682B4',
  [TERRAIN.WATER_T_L_B_LAND]: '#4682B4',
  [TERRAIN.WATER_L_T_R_LAND]: '#4682B4',
  [TERRAIN.WATER_L_B_R_LAND]: '#4682B4',
  [TERRAIN.WATER_ALL_LAND]: '#4682B4',
  [TERRAIN.SNOW_ROAD_T_B_R]: '#F0FFFF',
  [TERRAIN.SNOW_ROAD_L_T_R]: '#F0FFFF',
  [TERRAIN.SNOW_ROAD_L_R_B]: '#F0FFFF',
  [TERRAIN.SNOW_ROAD_T_B_L]: '#F0FFFF',
  [TERRAIN.SNOW_ROAD_END_T]: '#F0FFFF',
  [TERRAIN.SNOW_ROAD_END_B]: '#F0FFFF',
  [TERRAIN.SNOW_ROAD_END_R]: '#F0FFFF',
  [TERRAIN.SNOW_ROAD_END_L]: '#F0FFFF',
  [TERRAIN.SNOW_ROAD_H]: '#F0FFFF',
  [TERRAIN.SNOW_ROAD_V]: '#F0FFFF',
  [TERRAIN.SNOW_ROAD_CROSS]: '#F0FFFF',
  [TERRAIN.SNOW_ROAD_L_B]: '#F0FFFF',
  [TERRAIN.SNOW_ROAD_L_T]: '#F0FFFF',
  [TERRAIN.SNOW_ROAD_T_R]: '#F0FFFF',
  [TERRAIN.SNOW_ROAD_B_R]: '#F0FFFF',
};

export const TERRAIN_NAMES = {
  [TERRAIN.PLAIN]: 'Plain',
  [TERRAIN.FOREST]: 'Forest',
  [TERRAIN.MOUNTAIN]: 'Mountain',
  [TERRAIN.WATER]: 'Water',
  [TERRAIN.CASTLE]: 'Castle',
  [TERRAIN.VILLAGE]: 'Village',
  [TERRAIN.WATER_SHIMMER]: 'Water',
  [TERRAIN.WATER_SHIMMER_2]: 'Water',
  [TERRAIN.FOREST_3]: 'Forest',
  [TERRAIN.FOREST_2]: 'Forest',
  [TERRAIN.MOUNTAIN_HIGH]: 'Mountain',
  [TERRAIN.SNOW_PLAIN]: 'Snow Plain',
  [TERRAIN.MOUNTAIN_SMALL]: 'Mountain',
  [TERRAIN.VILLAGE_HEAL]: 'Village',
  [TERRAIN.CASTLE_2]: 'Castle',
  [TERRAIN.TEMPLE]: 'Temple',
  [TERRAIN.REEF_3]: 'Reef',
  [TERRAIN.REEF_2]: 'Reef',
  [TERRAIN.TEMPLE_WATER]: 'Water Temple',
  [TERRAIN.SNOW_ROAD_H]: 'Snow Road',
  [TERRAIN.SNOW_ROAD_V]: 'Snow Road',
  [TERRAIN.SNOW_ROAD_CROSS]: 'Snow Road',
  [TERRAIN.SNOW_ROAD_L_B]: 'Snow Road',
  [TERRAIN.SNOW_ROAD_L_T]: 'Snow Road',
  [TERRAIN.SNOW_ROAD_T_R]: 'Snow Road',
  [TERRAIN.SNOW_ROAD_B_R]: 'Snow Road',
  [TERRAIN.VILLAGE_RUIN]: 'Ruins',
  [TERRAIN.BRIDGE_H]: 'Bridge',
  [TERRAIN.BRIDGE_V]: 'Bridge',
  [TERRAIN.TEMPLE_HEAL]: 'Temple',
  [TERRAIN.SNOW_BUILDING_1]: 'Building',
  [TERRAIN.SNOW_BUILDING_2]: 'Building',
  [TERRAIN.SNOW_BUILDING_3]: 'Building',
  [TERRAIN.SNOW_BUILDING_4]: 'Building',
  [TERRAIN.TOWN]: 'Town'
};

export const TERRAIN_DEFENSE = {
  [TERRAIN.PLAIN]: 0,
  [TERRAIN.FOREST]: 20,
  [TERRAIN.MOUNTAIN]: 30,
  [TERRAIN.WATER]: -10,
  [TERRAIN.CASTLE]: 40,
  [TERRAIN.VILLAGE]: 30
};

export const TERRAIN_STATS = {
  [TERRAIN.PLAIN]: { defense: 5, cost: 1, type: 0 },
  [TERRAIN.FOREST]: { defense: 10, cost: 2, type: 2 },
  [TERRAIN.MOUNTAIN]: { defense: 15, cost: 3, type: 3 },
  [TERRAIN.WATER]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.CASTLE]: { defense: 15, cost: 1, type: 0 },
  [TERRAIN.VILLAGE]: { defense: 10, cost: 1, type: 0 },
  [TERRAIN.SNOW_ROAD_H]: { defense: 0, cost: 1, type: 0 },
  [TERRAIN.SNOW_ROAD_V]: { defense: 0, cost: 1, type: 0 },
  [TERRAIN.SNOW_ROAD_CROSS]: { defense: 0, cost: 1, type: 0 },
  [TERRAIN.SNOW_ROAD_L_B]: { defense: 0, cost: 1, type: 0 },
  [TERRAIN.SNOW_ROAD_L_T]: { defense: 0, cost: 1, type: 0 },
  [TERRAIN.SNOW_ROAD_T_R]: { defense: 0, cost: 1, type: 0 },
  [TERRAIN.SNOW_ROAD_B_R]: { defense: 0, cost: 1, type: 0 },
  [TERRAIN.VILLAGE_RUIN]: { defense: 10, cost: 1, type: 0 },
  [TERRAIN.BRIDGE_H]: { defense: 0, cost: 1, type: 1 },
  [TERRAIN.BRIDGE_V]: { defense: 0, cost: 1, type: 1 },
  [TERRAIN.TEMPLE_HEAL]: { defense: 10, cost: 1, type: 0 },
  [TERRAIN.SNOW_BUILDING_1]: { defense: 10, cost: 2, type: 0 },
  [TERRAIN.SNOW_BUILDING_2]: { defense: 15, cost: 1, type: 0 },
  [TERRAIN.SNOW_BUILDING_3]: { defense: 10, cost: 2, type: 0 },
  [TERRAIN.SNOW_BUILDING_4]: { defense: 10, cost: 1, type: 0 },
  [TERRAIN.TOWN]: { defense: 15, cost: 1, type: 0 },
  [TERRAIN.WATER_TL_BL_LAND]: { defense: 15, cost: 1, type: 0 },
  [TERRAIN.WATER_BL_BR_LAND]: { defense: 15, cost: 1, type: 0 },
  [TERRAIN.WATER_TR_BR_LAND]: { defense: 15, cost: 1, type: 0 },
  [TERRAIN.WATER_TL_TR_LAND]: { defense: 15, cost: 1, type: 0 },
  [TERRAIN.WATER_TL_BR_LAND]: { defense: 15, cost: 1, type: 0 },
  [TERRAIN.WATER_BL_TR_LAND]: { defense: 15, cost: 1, type: 0 },
  [TERRAIN.WATER_TL_TR_BL_LAND]: { defense: 15, cost: 1, type: 0 },
  [TERRAIN.WATER_TL_TR_BR_LAND]: { defense: 15, cost: 1, type: 0 },
  [TERRAIN.WATER_TR_BL_BR_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_TL_BL_BR_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_CORNERS_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_BL_BR_T_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_TL_TR_B_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_TL_BL_R_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_L_TR_BR_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_T_BR_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_T_BL_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_TL_B_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_TR_B_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_TL_R_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_BL_R_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_L_TR_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_L_BR_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_T_R_BL_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_TL_R_B_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_L_B_TR_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_L_T_BR_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_T_B_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_L_R_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_T_R_B_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_T_L_B_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_L_T_R_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_L_B_R_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_ALL_LAND]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.SNOW_ROAD_T_B_R]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.SNOW_ROAD_L_T_R]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.SNOW_ROAD_L_R_B]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.SNOW_ROAD_T_B_L]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.SNOW_ROAD_END_T]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.SNOW_ROAD_END_B]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.SNOW_ROAD_END_R]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.SNOW_ROAD_END_L]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.TEMPLE]: { defense: 10, cost: 1, type: 0 },
  [TERRAIN.REEF_3]: { defense: 10, cost: 3, type: 1 },
  [TERRAIN.REEF_2]: { defense: 10, cost: 3, type: 1 },
  [TERRAIN.TEMPLE_WATER]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_SHIMMER]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.WATER_SHIMMER_2]: { defense: 0, cost: 3, type: 1 },
  [TERRAIN.FOREST_3]: { defense: 10, cost: 2, type: 2 },
  [TERRAIN.FOREST_2]: { defense: 10, cost: 2, type: 2 },
  [TERRAIN.MOUNTAIN_HIGH]: { defense: 15, cost: 3, type: 3 },
  [TERRAIN.SNOW_PLAIN]: { defense: 5, cost: 1, type: 0 },
  [TERRAIN.MOUNTAIN_SMALL]: { defense: 10, cost: 3, type: 3 },
  [TERRAIN.VILLAGE_HEAL]: { defense: 10, cost: 1, type: 0 },
  [TERRAIN.CASTLE_2]: { defense: 15, cost: 1, type: 0 },
};

/*
export const UNIT_TYPES = {
  SOLDIER: 'soldier',
  ARCHER: 'archer',
  KNIGHT: 'knight',
  WOLF: 'wolf',
  CATAPULT: 'catapult',
  GHOST: 'ghost',
  SLIME: 'slime',
  MERMAID: 'mermaid',
  WATER_ELEMENTAL: 'water_elemental',
  DARK_MAGE: 'dark_mage',
  SORCERESS: 'sorceress',
*/
/*
  PALADIN: 'paladin',
  ELF: 'elf',
  BERSERKER: 'berserker',
  STONE_GOLEM: 'stone_golem',
  ICE_ELEMENTAL: 'ice_elemental',
  WOLF_RIDER: 'wolf_rider',
  DRAGON: 'dragon',
  KING: 'king',
  SKELETON: 'skeleton',
  DRUID: 'druid'
};
*/

export const TEAMS = {
  BLUE: 'blue',
  RED: 'red',
  GREEN: 'green',
  BLACK: 'black'
};

export const ATTACK_TYPES = {
  PHYSICAL: 'physical',
  MAGICAL: 'magical'
};

export const MOVE_TYPES = {
  LAND: 'land',
  WATER: 'water',
  AIR: 'air'
};

export const XP_THRESHOLDS = [100, 300, 600];

export const ABILITIES = {
  CASTLE_CAPTURER: 'castle_capturer',
  VILLAGE_CAPTURER: 'village_capturer',
  REPAIRER: 'repairer',
  DESTROYER: 'destroyer',
  MARKSMAN: 'marksman',
  AIR_UNIT: 'air_unit',
  UNDEAD: 'undead',
  SUMMONER: 'summoner',
  BLINDER: 'blinder',
  HEALER: 'healer',
  POISONER: 'poisoner',
  PURIFICATION_AURA: 'purification_aura',
  BATTLE_WILL: 'battle_will',
  COUNTER_STORM: 'counter_storm',
  GUARDIAN: 'guardian',
  HARD_SKIN: 'hard_skin',
  WEAKNESS_AURA: 'weakness_aura',
  WATER_CHILD: 'water_child',
  FOREST_CHILD: 'forest_child',
  MOUNTAIN_CHILD: 'mountain_child',
  EARTH_CHILD: 'earth_child',
  SELF_REPAIR: 'self_repair',
  ASSAULT_TROOP: 'assault_troop',
  SUPPORTER: 'supporter',
  MELEE_MASTER: 'melee_master',
  ATTACK_AURA: 'attack_aura',
  DEATH_REAPER: 'death_reaper'
};

export const UNIT_STATS = {
  [UNIT_TYPES.SOLDIER]: {
      move: 4,
      range: 1,
      attack: 55,
      physDef: 5,
      magDef: 5,
      cost: 150,
      population: 1,
      symbol: '⚔️',
      attackType: ATTACK_TYPES.PHYSICAL,
      moveType: MOVE_TYPES.LAND,
      abilities: [ABILITIES.VILLAGE_CAPTURER, ABILITIES.REPAIRER],
      levelUp: { attack: 10, defense: 5 },
      spriteAtlas: 'u0'
  },
  /*
  [UNIT_TYPES.KNIGHT]: {
      move: 6,
      range: 1,
      attack: 60,
      physDef: 15,
      magDef: 5,
      cost: 600,
      symbol: '🐴',
      attackType: ATTACK_TYPES.PHYSICAL,
      moveType: MOVE_TYPES.LAND,
      abilities: [ABILITIES.ASSAULT_TROOP],
      levelUp: { attack: 10, defense: 5 },
      spriteAtlas: 'u12'
  },
  */
  [UNIT_TYPES.GHOST]: {
      move: 4,
      range: 1,
      attack: 50,
      physDef: 5,
      magDef: 15,
      cost: 200,
      population: 1,
      symbol: '👻',
      attackType: ATTACK_TYPES.MAGICAL,
      moveType: MOVE_TYPES.AIR,
      abilities: [ABILITIES.AIR_UNIT, ABILITIES.UNDEAD, ABILITIES.DEATH_REAPER],
      levelUp: { attack: 10, defense: 5, move: 1 },
      spriteAtlas: 'u14'
  },
  [UNIT_TYPES.ARCHER]: {
      move: 4,
      range: [2, 3],
      attack: 45,
      physDef: 5,
      magDef: 5,
      cost: 250,
      population: 1,
      symbol: '🏹',
      attackType: ATTACK_TYPES.PHYSICAL,
      moveType: MOVE_TYPES.LAND,
      abilities: [ABILITIES.MARKSMAN],
      levelUp: { attack: 10, defense: 5 },
      spriteAtlas: 'u1'
  },
  [UNIT_TYPES.SLIME]: {
      move: 4,
      range: 1,
      attack: 50,
      physDef: 40,
      magDef: -20,
      cost: 250,
      population: 1,
      symbol: '💧',
      attackType: ATTACK_TYPES.MAGICAL,
      moveType: MOVE_TYPES.LAND,
      abilities: [ABILITIES.SELF_REPAIR],
      levelUp: { attack: 10, defense: 5, hp: 5 },
      spriteAtlas: 'u18'
  },
  [UNIT_TYPES.WATER_ELEMENTAL]: {
      move: 4,
      range: 1,
      attack: 60,
      physDef: 15,
      magDef: 15,
      cost: 300,
      population: 1,
      symbol: '🌊',
      attackType: ATTACK_TYPES.PHYSICAL,
      moveType: MOVE_TYPES.WATER,
      abilities: [ABILITIES.WATER_CHILD],
      levelUp: { attack: 10, defense: 5 },
      spriteAtlas: 'u2'
  },
  [UNIT_TYPES.DARK_MAGE]: {
      move: 4,
      range: 1,
      attack: 45,
      physDef: 0,
      magDef: 20,
      cost: 300,
      population: 1,
      symbol: '🧙‍♂️',
      attackType: ATTACK_TYPES.MAGICAL,
      moveType: MOVE_TYPES.LAND,
      abilities: [ABILITIES.BLINDER],
      levelUp: { attack: 10, defense: 5 },
      spriteAtlas: 'u15'
  },
  [UNIT_TYPES.SORCERESS]: {
      move: 4,
      range: [1, 2],
      attack: 45,
      physDef: 0,
      magDef: 40,
      cost: 400,
      population: 2,
      symbol: '🧙‍♀️',
      attackType: ATTACK_TYPES.MAGICAL,
      moveType: MOVE_TYPES.LAND,
      abilities: [ABILITIES.SUMMONER],
      levelUp: { attack: 5, defense: 5 },
      spriteAtlas: 'u3'
  },
  [UNIT_TYPES.PALADIN]: {
      move: 4,
      range: 1,
      attack: 50,
      physDef: 10,
      magDef: 10,
      cost: 400,
      population: 2,
      symbol: '🛡️',
      attackType: ATTACK_TYPES.PHYSICAL,
      moveType: MOVE_TYPES.LAND,
      abilities: [ABILITIES.VILLAGE_CAPTURER, ABILITIES.HEALER],
      levelUp: { attack: 5, defense: 5 },
      spriteAtlas: 'u12'
  },
  [UNIT_TYPES.ELF]: {
      move: 4,
      range: [1, 2],
      attack: 55,
      physDef: 20,
      magDef: 30,
      cost: 500,
      population: 2,
      symbol: '🧝',
      attackType: ATTACK_TYPES.MAGICAL,
      moveType: MOVE_TYPES.AIR,
      abilities: [ABILITIES.AIR_UNIT, ABILITIES.FOREST_CHILD, ABILITIES.PURIFICATION_AURA],
      levelUp: { attack: 5, defense: 5 },
      spriteAtlas: 'u4'
  },
  [UNIT_TYPES.BERSERKER]: {
      move: 5,
      range: 1,
      attack: 70,
      physDef: 20,
      magDef: 10,
      cost: 500,
      population: 2,
      symbol: '🪓',
      attackType: ATTACK_TYPES.PHYSICAL,
      moveType: MOVE_TYPES.LAND,
      abilities: [ABILITIES.BATTLE_WILL, ABILITIES.COUNTER_STORM, ABILITIES.EARTH_CHILD],
      levelUp: { attack: 10, defense: 5 },
      spriteAtlas: 'u13'
  },
  [UNIT_TYPES.WOLF]: {
      move: 6,
      range: 1,
      attack: 75,
      physDef: 20,
      magDef: 10,
      cost: 600,
      population: 3,
      symbol: '🐺',
      attackType: ATTACK_TYPES.PHYSICAL,
      moveType: MOVE_TYPES.LAND,
      abilities: [ABILITIES.POISONER, ABILITIES.ASSAULT_TROOP, ABILITIES.EARTH_CHILD],
      levelUp: { attack: 10, defense: 5 },
      spriteAtlas: 'u5'
  },
  [UNIT_TYPES.STONE_GOLEM]: {
      move: 5,
      range: 1,
      attack: 55,
      physDef: 30,
      magDef: 10,
      cost: 600,
      population: 3,
      symbol: '🗿',
      attackType: ATTACK_TYPES.PHYSICAL,
      moveType: MOVE_TYPES.LAND,
      abilities: [ABILITIES.GUARDIAN, ABILITIES.MOUNTAIN_CHILD, ABILITIES.WEAKNESS_AURA],
      levelUp: { attack: 5, defense: 5, hp: 25 },
      spriteAtlas: 'u6'
  },
  [UNIT_TYPES.ICE_ELEMENTAL]: {
      move: 4,
      range: [1, 3],
      attack: 55,
      physDef: 10,
      magDef: 20,
      cost: 600,
      population: 3,
      symbol: '❄️',
      attackType: ATTACK_TYPES.MAGICAL,
      moveType: MOVE_TYPES.WATER,
      abilities: [ABILITIES.WATER_CHILD, ABILITIES.SELF_REPAIR],
      levelUp: { attack: 10, defense: 5, hp: 10 },
      spriteAtlas: 'u17'
  },
  [UNIT_TYPES.CATAPULT]: {
      move: 3,
      range: [3, 5],
      attack: 60,
      physDef: 5,
      magDef: 5,
      cost: 800,
      population: 4,
      symbol: '☄️',
      attackType: ATTACK_TYPES.PHYSICAL,
      moveType: MOVE_TYPES.LAND,
      abilities: [ABILITIES.DESTROYER],
      levelUp: { attack: 10, defense: 5 },
      spriteAtlas: 'u7'
  },
  [UNIT_TYPES.WOLF_RIDER]: {
      move: 6,
      range: [1, 3],
      attack: 60,
      physDef: 20,
      magDef: 10,
      cost: 800,
      population: 4,
      symbol: '🏇',
      attackType: ATTACK_TYPES.PHYSICAL,
      moveType: MOVE_TYPES.LAND,
      abilities: [ABILITIES.MARKSMAN, ABILITIES.FOREST_CHILD, ABILITIES.ASSAULT_TROOP, ABILITIES.BLINDER],
      levelUp: { attack: 10, defense: 5 },
      spriteAtlas: 'u16'
  },
  [UNIT_TYPES.DRAGON]: {
      move: 6,
      range: [1, 2],
      attack: 70,
      physDef: 25,
      magDef: 25,
      cost: 1000,
      population: 5,
      symbol: '🐉',
      attackType: ATTACK_TYPES.MAGICAL,
      moveType: MOVE_TYPES.AIR,
      abilities: [ABILITIES.AIR_UNIT, ABILITIES.MELEE_MASTER, ABILITIES.GUARDIAN, ABILITIES.ASSAULT_TROOP],
      levelUp: { attack: 10, defense: 5 },
      spriteAtlas: 'u8'
  },
  [UNIT_TYPES.KING]: {
      move: 4,
      range: 1,
      attack: 60,
      physDef: 20,
      magDef: 20,
      cost: 400,
      population: 0,
      symbol: '👑',
      attackType: ATTACK_TYPES.PHYSICAL,
      moveType: MOVE_TYPES.LAND,
      abilities: [ABILITIES.CASTLE_CAPTURER, ABILITIES.VILLAGE_CAPTURER, ABILITIES.REPAIRER],
      levelUp: { attack: 10, defense: 5, move: 1 },
      spriteAtlas: 'u9'
  },
  [UNIT_TYPES.SKELETON]: {
      move: 3,
      range: 1,
      attack: 40,
      physDef: 5,
      magDef: 5,
      cost: 0,
      population: 0,
      symbol: '💀',
      attackType: ATTACK_TYPES.PHYSICAL,
      moveType: MOVE_TYPES.LAND,
      abilities: [ABILITIES.POISONER, ABILITIES.UNDEAD],
      levelUp: { attack: 10, defense: 5 },
      spriteAtlas: 'u10'
  },
  [UNIT_TYPES.MERMAID]: { 
      move: 4, range: [1, 2], attack: 40, physDef: 0, magDef: 0, cost: 200, population: 1, symbol: '🧜', 
      attackType: ATTACK_TYPES.PHYSICAL, moveType: MOVE_TYPES.WATER, 
      abilities: [ABILITIES.VILLAGE_CAPTURER, ABILITIES.REPAIRER, ABILITIES.WATER_CHILD],
      levelUp: { attack: 10, defense: 5 },
      spriteAtlas: 'u19'
  },
  [UNIT_TYPES.DRUID]: { 
      move: 4, range: [1, 2], attack: 40, physDef: 0, magDef: 30, cost: 600, population: 3, symbol: '🐻', 
      attackType: ATTACK_TYPES.MAGICAL, moveType: MOVE_TYPES.LAND, 
      abilities: [ABILITIES.ATTACK_AURA, ABILITIES.EARTH_CHILD, ABILITIES.SUPPORTER],
      levelUp: { attack: 5, defense: 5, move: 1 },
      spriteAtlas: 'u20'
  },
  [UNIT_TYPES.WISDOM_CRYSTAL]: {
      move: 4,
      range: 0,
      attack: 0,
      physDef: 10,
      magDef: 10,
      cost: 200,
      population: 0,
      symbol: '💎',
      attackType: ATTACK_TYPES.MAGICAL,
      moveType: MOVE_TYPES.LAND,
      abilities: [ABILITIES.SUPPORTER],
      levelUp: { attack: 0, defense: 5 },
      spriteAtlas: 'u11'
  }
};

export const TEAM_COLORS = {
  [TEAMS.BLUE]: '#3498db',
  [TEAMS.RED]: '#e74c3c',
  [TEAMS.GREEN]: '#2ecc71',
  [TEAMS.BLACK]: '#2c3e50'
};

export const UNIT_DESCRIPTIONS = {
  [UNIT_TYPES.SOLDIER]: "Basic infantry. Balanced stats.",
  [UNIT_TYPES.ARCHER]: "Ranged attacker. Can attack from distance.",
  [UNIT_TYPES.KNIGHT]: "Heavy cavalry. High mobility and defense.",
  [UNIT_TYPES.MAGE]: "Magic user. Attacks ignore physical defense.",
  [UNIT_TYPES.CATAPULT]: "Siege weapon. Long range, massive damage.",
  [UNIT_TYPES.WOLF_RIDER]: "Fast raider. Excellent in forests.",
  [UNIT_TYPES.DRAGON]: "Legendary beast. Dominates the skies.",
  [UNIT_TYPES.KING]: "Your commander. Must survive.",
  [UNIT_TYPES.SKELETON]: "Undead warrior. Weak but expendable.",
  [UNIT_TYPES.MERMAID]: "Water spirit. Masters of the sea.",
  [UNIT_TYPES.DRUID]: "Nature's guardian. Supports allies.",
  [UNIT_TYPES.WISDOM_CRYSTAL]: "Ancient artifact. Provides magical support.",
  [UNIT_TYPES.PALADIN]: "Holy warrior. Heals allies.",
  [UNIT_TYPES.ELF]: "Forest dweller. Agile and deadly.",
  [UNIT_TYPES.BERSERKER]: "Fierce warrior. High attack power.",
  [UNIT_TYPES.WOLF]: "Wild beast. Fast and dangerous.",
  [UNIT_TYPES.STONE_GOLEM]: "Living rock. Extremely durable.",
  [UNIT_TYPES.ICE_ELEMENTAL]: "Frozen spirit. Slows enemies.",
  [UNIT_TYPES.WATER_ELEMENTAL]: "Fluid form. Hard to hit.",
  [UNIT_TYPES.DARK_MAGE]: "Wielder of dark arts. Curses enemies.",
  [UNIT_TYPES.SORCERESS]: "Master of arcane. Summons creatures.",
  [UNIT_TYPES.GHOST]: "Ethereal spirit. Passes through walls.",
  [UNIT_TYPES.SLIME]: "Sticky nuisance. Splits when hit."
};

export const UNIT_QUOTES = {
  [UNIT_TYPES.SOLDIER]: "Soldiers are very useful in the early game, they can capture or repair villages to give you advantage.",
  [UNIT_TYPES.ARCHER]: "Archers can attack from distance, making them excellent for holding choke points.",
  [UNIT_TYPES.KNIGHT]: "Knights are the backbone of any offensive army, with high mobility and defense.",
  [UNIT_TYPES.MAGE]: "Mages can pierce through heavy armor, making them essential against high defense units.",
  [UNIT_TYPES.CATAPULT]: "Catapults can devastate enemy ranks from afar, but are vulnerable to direct attacks.",
  [UNIT_TYPES.WOLF_RIDER]: "Wolf Riders are masters of the forest, using their speed to outmaneuver enemies.",
  [UNIT_TYPES.DRAGON]: "Dragons are the ultimate unit, capable of flying over any terrain and dealing massive damage.",
  [UNIT_TYPES.KING]: "The King is the heart of your army. Protect him at all costs.",
  [UNIT_TYPES.SKELETON]: "Skeletons are weak individually, but can be summoned in large numbers to overwhelm the enemy.",
  [UNIT_TYPES.MERMAID]: "Mermaids rule the waters, gaining significant bonuses when fighting in their element.",
  [UNIT_TYPES.DRUID]: "Druids are versatile support units, able to buff allies and control the battlefield.",
  [UNIT_TYPES.WISDOM_CRYSTAL]: "Wisdom Crystals provide magical support, enhancing the capabilities of nearby spellcasters.",
  [UNIT_TYPES.PALADIN]: "Paladins are holy warriors who can heal their allies and smite the undead.",
  [UNIT_TYPES.ELF]: "Elves are at home in the forest, gaining bonuses to defense and movement.",
  [UNIT_TYPES.BERSERKER]: "Berserkers deal massive damage but have low defense. Use them to break enemy lines.",
  [UNIT_TYPES.WOLF]: "Wolves are fast and deadly, perfect for hunting down weakened enemies.",
  [UNIT_TYPES.STONE_GOLEM]: "Stone Golems are nearly impervious to physical attacks, but weak against magic.",
  [UNIT_TYPES.ICE_ELEMENTAL]: "Ice Elementals can freeze enemies, slowing their advance.",
  [UNIT_TYPES.WATER_ELEMENTAL]: "Water Elementals are fluid and hard to hit, especially when in water.",
  [UNIT_TYPES.DARK_MAGE]: "Dark Mages use forbidden magic to curse and weaken their foes.",
  [UNIT_TYPES.SORCERESS]: "Sorceresses can summon magical creatures to fight for them.",
  [UNIT_TYPES.GHOST]: "Ghosts can move through walls and obstacles, making them excellent scouts.",
  [UNIT_TYPES.SLIME]: "Slimes are annoying pests that can split into smaller slimes when hit."
};

export const TERRAIN_DESCRIPTIONS = {
  [TERRAIN.PLAIN]: "Open field. No movement penalty.",
  [TERRAIN.FOREST]: "Dense trees. Provides cover.",
  [TERRAIN.MOUNTAIN]: "Rocky terrain. High defense bonus.",
  [TERRAIN.WATER]: "Deep water. Impassable for most.",
  [TERRAIN.CASTLE]: "Fortified base. Generates income and heals units.",
  [TERRAIN.VILLAGE]: "Local settlement. Heals units.",
  [TERRAIN.TOWN]: "Large settlement. Generates income and heals units.",
  [TERRAIN.SNOW_PLAIN]: "Frozen ground. Cold and slippery.",
  [TERRAIN.WATER_SHIMMER]: "Mystical waters. Shimmers with magic.",
  [TERRAIN.TEMPLE]: "Ancient ruins. Holds mysterious power.",
  [TERRAIN.REEF_3]: "Coral reef. Dangerous for ships.",
  [TERRAIN.BRIDGE_H]: "Wooden bridge. Crosses water.",
  [TERRAIN.BRIDGE_V]: "Wooden bridge. Crosses water.",
  [TERRAIN.VILLAGE_RUIN]: "Ruined village. Can be repaired.",
  [TERRAIN.VILLAGE_HEAL]: "Healing spring. Restores health.",
  [TERRAIN.TEMPLE_HEAL]: "Sacred ground. Restores health."
};

export const TERRAIN_QUOTES = {
  [TERRAIN.PLAIN]: "The vast plains are perfect for large scale maneuvers.",
  [TERRAIN.FOREST]: "The forest is a natural fortress, providing cover for those who know how to use it.",
  [TERRAIN.MOUNTAIN]: "High ground offers a significant tactical advantage.",
  [TERRAIN.WATER]: "The sea is a harsh mistress, but she protects her own.",
  [TERRAIN.CASTLE]: "A castle is the heart of any kingdom. Defend it with your life.",
  [TERRAIN.VILLAGE]: "Villages provide the resources needed to sustain an army.",
  [TERRAIN.TOWN]: "Towns are bustling hubs of activity and commerce.",
  [TERRAIN.SNOW_PLAIN]: "The cold bites deep, but the snow offers its own kind of protection.",
  [TERRAIN.TEMPLE]: "The ancients left behind more than just ruins.",
  [TERRAIN.VILLAGE_RUIN]: "War has taken its toll, but this village can be rebuilt.",
  [TERRAIN.VILLAGE_HEAL]: "The waters here have miraculous healing properties.",
  [TERRAIN.TEMPLE_HEAL]: "This holy site has been a place of healing for centuries."
};
